### ISSUE TITLE
Define a set of musical notes for onset and pitch detection assessment

### ISSUE THREAD

**Issue by Nuopel** [Aluriak/MusicGenerator#6]
Define a test set of musical notes knowing the notes places and pitch of the notes
to be able to perform qualitative assessment of the different methods.
--> use midi to generate different piano samples (look if not to good)
--> format of notes pitch and pos ?
     |.txt with 2 columns: pos and pitch

**Comment by Nuopel** [comment]
After some troubles , sometimes the note positions seemed wrong compared to the wav, I selected 8 samples to be the tests for the onset and pitch detection.
-5 with a low density of notes
-3 with a high density of notes

They were generated using respectively the mendel and the chopin midi
 present in the /AudioRessources folder  and are located in a subfolder /AudioRessources/EvaluationData.

The midi have been converted into mp3 using https://solmire.com/, then in wav using audacity

**Comment by Aluriak** [comment]
Why not use [timidity](https://wiki.archlinux.org/index.php/Timidity) to convert midi to wave directly with something like: 

    timidity -Ow -o output.wav input.mid

**Comment by Nuopel** [comment]
Yes! I was lazy to find the command ^^'
